version: '2'
services:
  db:
    build: ./docker/database/
    volumes:
      - ./.data:/var/lib/postgresql/data
  redis:
    image: redis:3.2
    command: redis-server --appendonly yes
    volumes:
      - ./.data:/data
    ports:
      - "6379:6379"
  statsd:
    image: python:2.7.13
    volumes:
      - .:/opt/rowboat
    command: python /opt/rowboat/docker/nulld.py
    ports:
      - "8125:8125"
    stop_signal: SIGKILL
  web:
    build: .
    command: python manage.py serve -r
    volumes:
      - .:/opt/rowboat
    ports:
      - "8686:8686"
    depends_on:
      - db
      - redis
      - statsd
  bot:
    build: .
    command: python manage.py bot -e docker
    volumes:
      - .:/opt/rowboat
    ports:
      - "7171:7171"
    depends_on:
      - web
  workers:
    build: .
    command: python manage.py workers
    volumes:
      - .:/opt/rowboat
    depends_on:
      - web
