version: 2

machine:
  services:
    - redis


notify:
  webhooks:
    - url: https://rowboat.party/webhooks/circle_ci

jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: python:2.7.13
    steps:
      - checkout
      - restore_cache:
          key: rowboat-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: "Install Dependencies"
          command: pip install -r requirements.txt
      - save_cache:
          key: rowboat-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: "Setup JUnit Path"
          command: mkdir -p /tmp/results/junit/
      - run:
          name: "Run Tests"
          command: py.test tests --junitxml /tmp/results/junit/rowboat.xml
      - store_test_results:
          path: /tmp/results
